**Numpy(Numeric Python):** Open Source python Library for higher level mathematical function (scientific computing).

**Array:** An array is a data structure that stores values of same data type.

**The key feature of Numpy is** 
- Support for **multi-dimensional arrays**. This is useful for representing vectors and matrices.
- Numpy also gives us a number of operations which we can perform on matrices. This includes obvious things from linear algebra like adding, multiplying, subtracting of matrices and vectors, but also includes optimized statistical operations fast Fourier transforms among others.
- When working with matrices and vectors we must is making sure their dimensions(rows,columns) align properly. Numpy makes the process easier and the code easier to read by supporting something called **broadcasting**(it describes how numpy treats arrays with different shapes during arithmetic operations)

**Goal**
- Create both rank one and rank two ndarrays use built-in functions to create ndarrays with different shapes and initial values.
- Access element in ndarrays using basic indexing.

**Benefits**
- Numpy is often fast enough for production code, so we don't need to optimize further,
- Numpy is fast (using Numpy's arrays can be 10 times faster than Python's lists)
   - Numpy arrays are fixed in size(unlike lists which can change in size)
   - Numpy arrays elements must all be the same type(where as lists can hold any type)
- ndarrays both much more space efficient than lists, but also opens up a range of memory and computational optimizations.
- functionality:
   - Average of a vector or the matrix?
   - Want to multiply matrices?
   - Want to select a subset of the matrix based on indexes or values?

**Import:** Import the NumPy package as np and then use np to access the functions from that package.

In [2]:
import numpy as np

**Rank one** ndarrays are simply a single dimensional array or a vector.

- In order to create an ndarray, we call the function in numpy called **array**, which returns the ndarray object.

In [2]:
array1= np.array([10.2, 20, 30])
# array1= np.array([10.2, 20, 30], dtype= np.int64)
array1

array([10.2, 20. , 30. ])

#### Examining properties of matrix:
- **Check dimension of array:**

In [3]:
array1.ndim

1

- **Check datatype of array:**

In [4]:
type(array1)

numpy.ndarray

- **Check shape of array:**

In [5]:
array1.shape

(3,)

since 1D array has only row hence above we have three column of array1.

- **Check datatype of elements of array:**

In [6]:
array1.dtype

dtype('float64')

- **Check size of each element or item:**

In [7]:
array1.itemsize

8

- **Check size of array or total no. of elements in array**

In [8]:
array1.size

3

**Accessing the elements**:

In [9]:
array1[0]

10.2

- Slice indexing

In [10]:
print(array1[:-1])
array1[:-1]

[10.2 20. ]


array([10.2, 20. ])

**NOTE: ndarrays are mutable, which means that we can switch their elements** using an assignment.

In [11]:
array1[2]= 40

In [12]:
array1 # changed array

array([10.2, 20. , 40. ])

**NOTE:**
array1[2]= 'hi' **will generate invalid literal for int() error**

**Element Wise Operation**

In [13]:
array1+2

array([12.2, 22. , 42. ])

In [14]:
array1**2

array([ 104.04,  400.  , 1600.  ])

**NOTE: These operations will not change the original matrix. Hence in order to reuse we have to save it before.**

In [15]:
array1

array([10.2, 20. , 40. ])

### Create 1D array using arange():
   - syntax: array_name= np.arange(start,stop+1,step)

In [16]:
array2= np.arange(1,10,2)
array2

array([1, 3, 5, 7, 9])

### Create equally spaced array between two no.:
     - Syntax: array_name=np.linspace(start no.,stop no.,total no.s required including start & stop)

In [17]:
import numpy as np
# np.set_printoptions(precision= 2)
array3= np.linspace(0,1,10)
array3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

A **rank two array** is a two dimensional array, which is effectively a matrix.

- we create a 2D array, using nested brackets.

In [18]:
array4= np.array([[1,2,3], [4,5,6]])
array4

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array4.ndim

2

In [20]:
type(array4)

numpy.ndarray

In [21]:
array4.shape

(2, 3)

since 2D array consist of rows and column hence above we have 2 rows and 3 columns.

In [22]:
array4.dtype

dtype('int32')

In [23]:
array4.itemsize

4

In [24]:
array4.size

6

**Accessing the elements:**

In [25]:
array4[0,0]

1

Use **slice indexing** to get subsets of those data structures

In [26]:
array5= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
array5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- slice indexing to get a submatrix:
    - Syntax as array_name[row start:row stop:step, column start: column stop:step]
    - Syntax as array_name[[required sequential row_index seperated by comma],[required sequential column_index seperated by comma]]

In [27]:
# [1, 2]
# [5, 6]
array6= array5[:2, :2]
array6

array([[1, 2],
       [5, 6]])

In [28]:
array6[0,0]= 100
array5

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

- Hence slices are just references to the same underlying data as the original array.
- But if you actually don't want to change the original array then make copy of slice as below,

In [29]:
array7= np.array(array5[:2, :2])
array7

array([[100,   2],
       [  5,   6]])

In [30]:
array7[0,0]= 10
array5

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [31]:
# [6, 7, 8]
# [10,11,12]
array5[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [32]:
# [2, 4]
# [10,12]
array5[0::2, 1::2]

array([[ 2,  4],
       [10, 12]])

In [33]:
# [11,10]
# [3, 2]
array5[-1::-2, 2:-4:-1]

array([[11, 10],
       [ 3,  2]])

- **Use both Integer indexing and slicing:**

In [34]:
array5[1, :]

array([5, 6, 7, 8])

In [35]:
array5[1, :].shape

(4,)

i.e, a 1D array

In [36]:
array5[1:2, :]

array([[5, 6, 7, 8]])

In [37]:
array5[1:2, :].shape

(1, 4)

i.e, a 2D array

### Array Indexing for changing elements:

In [38]:
array8= np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
array8

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

- creating an array indices:

In [39]:
col_indices= np.array([0, 1, 2, 0])
row_indices= np.arange(4)

-  pairings the row and column indices

In [40]:
for row, col in zip(row_indices, col_indices):
    print(row, ",", col)

0 , 0
1 , 1
2 , 2
3 , 0


- selecting element from each row for above created indices pair

In [41]:
array8[row_indices, col_indices]

array([11, 22, 33, 41])

- now we can access elements using arrays as indices and also change the values of element at indices selected

In [42]:
array8[row_indices, col_indices] += 100
array8

array([[111,  12,  13],
       [ 21, 122,  23],
       [ 31,  32, 133],
       [141,  42,  43]])

### Other methods to create numpy array: Using builtin Numpy functions,

- Create a 2X2 array of zero's/Null matrix:

In [43]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

- Create a 2X2 array filled with 2.2

In [44]:
np.full((2,2), 2.2)

array([[2.2, 2.2],
       [2.2, 2.2]])

- Create a 2x2 Identity/unit matrix:

In [45]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

- Create 3x2 matrix of one's:

In [46]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- Create an array of random float between 0 & 1:

In [47]:
np.random.random((3,2))

array([[0.14718768, 0.48507717],
       [0.55602043, 0.87020364],
       [0.20677042, 0.45732477]])

### Basic opertions on Matrices:
**NOTE: Arrays must have same dimension or specified constrains**

In [48]:
array9= np.array([[10, 20, 30], [40, 50, 60]])
array10= np.array([[100, 200, 300], [400, 500, 600]])

- **Arithmetic Array Operations:**

In [49]:
array9+ array10
# np.add(array9, array10)

array([[110, 220, 330],
       [440, 550, 660]])

In [50]:
# array10- array9
np.subtract(array10, array9)

array([[ 90, 180, 270],
       [360, 450, 540]])

In [51]:
array9*array10
# np.multiply(array9, array10)

array([[ 1000,  4000,  9000],
       [16000, 25000, 36000]])

In [52]:
array10/array9
# np.divide(array9, array10)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [53]:
np.sqrt(array9)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [54]:
# exponent
np.exp(array10)

array([[2.68811714e+043, 7.22597377e+086, 1.94242640e+130],
       [5.22146969e+173, 1.40359222e+217, 3.77302030e+260]])

- **Basic Statistical operation:**

In [55]:
array9.mean()  # mean for all element

35.0

In [56]:
array9.mean(axis= 0)  # mean by column

array([25., 35., 45.])

In [57]:
array9.mean(axis= 1)  # mean by row

array([20., 50.])

In [58]:
np.median(array9, axis= 1)

array([20., 50.])

In [59]:
array9.sum()

210

In [60]:
array9.max()

60

In [61]:
array9.min()

10

- **Array sorting:**

In [62]:
import numpy as np
array11= np.array([[30,10,20], [40,80,60]])
array11

array([[30, 10, 20],
       [40, 80, 60]])

To avoid changing array values themselves in original. first we create a copy then copy is sorted, but the original is untouched.

In [63]:
array12= np.array(array11) # copy

In [64]:
array12.sort()    #axis=0,1 for column-wise or row-wise sorting. default rowwise
array12

array([[10, 20, 30],
       [40, 60, 80]])

- **Matix/Array Dot Product:**

In [65]:
array13= np.array([[1,2,3],[5,6,7]])
array14= np.array([[7,6],[5,4],[3,2]])
print(np.dot(array13, array14))
# Or
print(array13@ array14)

[[26 20]
 [86 68]]
[[26 20]
 [86 68]]


- **Transpose of an array:** Transpose is interchanging row into column

In [66]:
array13

array([[1, 2, 3],
       [5, 6, 7]])

In [67]:
array13.T

array([[1, 5],
       [2, 6],
       [3, 7]])

- **Concatenate Array:**
    - Syntax: np.concatenate((array1,array2),axis=?)
        - axis=1 for row wise concatenate
        - axis=0 for column wise concatenate
    - Syntax: np.vstack((array1,array2)) for vertical concatenate
    - Syntax: np.hstack((array1,array2)) for horizontal concatenate

In [68]:
array15= np.array([[1,2,3],[5,6,7]])
array16= np.array([[7,6,8],[5,4,1]])

In [69]:
np.concatenate((array15, array16),axis=1)

array([[1, 2, 3, 7, 6, 8],
       [5, 6, 7, 5, 4, 1]])

In [70]:
np.vstack((array15, array16))

array([[1, 2, 3],
       [5, 6, 7],
       [7, 6, 8],
       [5, 4, 1]])

- **Reshape array:**

In [71]:
array15.reshape(1,6)

array([[1, 2, 3, 5, 6, 7]])

### Boolean Indexing:

In [72]:
array17= np.array([[10, 11, 2, 5], [5, 7, 9, 4], [12, 5, 10, 6]])

- **Check each element for given condition and return true or false**

In [73]:
bool_x= array17>5
bool_x

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True, False,  True,  True]])

In [74]:
bool_x.dtype

dtype('bool')

- **Check each element for given condition and return values which satisfy condition**

In [75]:
array17[array17>5]

array([10, 11,  7,  9, 12, 10,  6])

In [76]:
array17[(array17>3) & (array17<8)]

array([5, 5, 7, 4, 5, 6])

     *Using boolean indexing for changing elements under given condition:

In [77]:
array17[array17%2== 0] += 10   # adding 10 to all even values
array17

array([[20, 11, 12,  5],
       [ 5,  7,  9, 14],
       [22,  5, 20, 16]])

- **Return index no. of row and column for given condition true values**

In [78]:
np.where(array17>5)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 1, 2, 3, 0, 2, 3], dtype=int64))

**NOTE: Special Case of reshape:**

In [79]:
array18= np.arange(1,7)
print(array18)
print(array18.ndim)

[1 2 3 4 5 6]
1


In [80]:
print(array18.reshape(-1,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- -1 in row as (-1,something) or column as (something,-1) is for unknown row or unknown column respectively

### Finding unique elements of array:
- **unique():** Return unique values of array

In [3]:
array19= np.array([1,3,4,5,3,5,1,6,7,8])

In [4]:
np.unique(array19)

array([1, 3, 4, 5, 6, 7, 8])

In [6]:
np.unique(array19, return_counts=True)

(array([1, 3, 4, 5, 6, 7, 8]), array([2, 2, 1, 2, 1, 1, 1], dtype=int64))

- **bincount():** Return frequency of unique values sequentially giving 0 for missing whole number in between two

In [83]:
np.bincount(array19)

array([0, 2, 0, 2, 1, 2, 1, 1, 1], dtype=int64)

### Convert 2-D array into 1-D array:

In [84]:
array20=np.array([[1,2,3],[4,5,6]])
print(array20)
print(array20.ndim)

[[1 2 3]
 [4 5 6]]
2


In [85]:
array20.tolist() # first Convert array into list

[[1, 2, 3], [4, 5, 6]]

In [86]:
array20.flatten() # Second merge list of list into 1 list convert into 1D

array([1, 2, 3, 4, 5, 6])

In [87]:
array20.flatten().tolist() # Mergin both above steps

[1, 2, 3, 4, 5, 6]

### Set Operation on Array:

In [88]:
set1= np.array(['mango', 'apple', 'apple', 'grapes', 'mint'])
set2= np.array(['red', 'blue', 'mint', 'green', 'green'])

In [89]:
np.union1d(set1, set2)

array(['apple', 'blue', 'grapes', 'green', 'mango', 'mint', 'red'],
      dtype='<U6')

In [90]:
np.intersect1d(set1, set2)

array(['mint'], dtype='<U6')

In [91]:
np.setdiff1d(set1, set2)  # Elements in set1 that are not in set2

array(['apple', 'grapes', 'mango'], dtype='<U6')

In [92]:
np.in1d(set1, set2)   # Elements in set1 that are in set2 # Return array of boolean

array([False, False, False, False,  True])

### Broadcasting: Broadcasting is one of the more advanced features to NumPy.
- Broadcasting aims to solve the mismatch in sizes/dimension between arrays.
- Rule: When operating on two arrays, Numpy compares their shapes elemen-wise.
     - It starts with the trailing dimensions and works its way forward.
     - Two dimensions are compatible when:
        1. they are equal, or
        2. one of them is 1(needs to be a scaler).

In [93]:
start= np.zeros((4,3))

In [94]:
add_rows= np.array([1, 0, 2])

In [95]:
x= start+ add_rows # will add to each row of 'start' using broadcasting
x

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [96]:
add_cols= np.array([[0,1,2,3]])
add_cols= add_cols.T

In [97]:
y= start + add_cols # will add to each column of 'start' using broadcast
y

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [98]:
add_scalar= np.array([1])

In [99]:
z= start + add_scalar
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])